# This is a basic workflow to help you get started with Actions

name: Manually Publish Nuget

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # Install DotNet 5 SDK
      - name: Setup dotnet 5.0.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
          
      # Restore Dependancies (can be omitted is you remove --no-restore on build step)
      - name: Restore package dependencies
        run: dotnet restore

      # Build the project
      - name: dotet build
        run: dotnet build --no-restore --configuration Release

      # Pack the project for Nuget
      - name: dotnet pack
        if: success()  # this should be implied, but adding just to be sure this runs only when the previous steps are successfull
        run: dotnet pack -v normal -c Release --no-restore --include-source -p:PackageVersion=$GITHUB_RUN_ID -o ${{env.DOTNET_ROOT}}/myapp 
      
      # Upload the artifact to a GitHub 'Nuget' artifact repo
      - name: Upload a Build Artifact
        run: dotnet nuget push ${{env.DOTNET_ROOT}}/myapp/*.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --source https://nuget.pkg.github.com/joelbyford/BasicAuth/index.json --skip-duplicate
        
      
